runtime: php55
api_version: 1

handlers:

- url: /css
  static_dir: css

- url: /fonts
  static_dir: fonts

- url: /img/(.*\.(ico$|jpg$|png$|gif$))
  static_files: img/\1
  upload: img/(.*\.(ico$|jpg$|png$|gif$))


- url: /js
  static_dir: js

- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /
  script: accion.php

- url: /(.+\.php)$
  script: \1

- url: /(.+\.html)$
  script: \1
